[project]
name = "msdocs-python-fastapi-webapp-quickstart"
version = "0.1.0"
requires-python = "==3.13.5"
dependencies = [
    "fastapi>=0.119.0",
    "jinja2>=3.1.6",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
